### ISSUE TITLE
requests.exceptions.SSLError SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by srepho** [Buzzilla/webhose-python#1]
When trying to use this package I get an error related stating:

```requests.exceptions.SSLError SSL: CERTIFICATE_VERIFY_FAILED```

I tried to disable requests warnings but this did not work. Is there anyway to use this package or should I switch directly to requests to manually remove the warnings?

**Comment by rangeva** [comment]
It might be an issue with the homebrew version of Python. What version of Python are you using? What version of openssl?

**Comment by srepho** [comment]
I tried it using Python 3.4.1 via Anaconda on Windows 7 and also Python 3.4.x via PythonAnywhere. My pyopenssl is 0.15.1 and I will look into what the SSL version is and get back to you. I was able to get it work by running a search string directly in Requests and setting verify=False.
