### ISSUE TITLE
since parameter doesn't work

### ISSUE THREAD

**Issue by sruteesh** [Buzzilla/webhose-python#9]
I am trying to search for articles written last week, but webhose retrieves data for last month always.
start_date = (2016,9,15)
r = webhose.search("thread.title:"+tag + " language:english site_type:blogs",since=dt2ts(start_date)).
Anyone else facing such issue?

**Comment by rangeva** [comment]
Make sure dt2ts returns the time stamp in milliseconds.

**Comment by sruteesh** [comment]
it does return in ms

**Comment by sruteesh** [comment]
Thanks @rangeva . I was able to rectify it. Earlier it returned in secs. Changed it to ms and it works fine now.
